version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/huobi_bot/
hooks:
  AfterInstall:
   - location: scripts/setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root