export const STOP_LOSS_DEVIATION = 3; // 3 (%)
export const SAFE_STOP_LOSS_DEVIATION = 1; // 1 (%)

export const LONG_STOP_LOSS_DEVIATION = -STOP_LOSS_DEVIATION;
export const SHORT_STOP_LOSS_DEVIATION = +STOP_LOSS_DEVIATION;

export const LONG_SAFE_STOP_LOSS_DEVIATION = -SAFE_STOP_LOSS_DEVIATION;
export const SHORT_SAFE_STOP_LOSS_DEVIATION = +SAFE_STOP_LOSS_DEVIATION;